config/routes.rb
Rails.application.routes.draw do
  resources :title_basics
  resources :players
  root to: 'home#index'
  #get '/name_basics', to: 'name_basics#index'
  post '/process', to: 'trades#create'
  post '/', to: 'errors#routing'

  # catch all
  match '*a', to: 'errors#routing', via: [:get, :post]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/name_basic.rb
class NameBasic < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
end

app/models/title_basic.rb
class TitleBasic < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActionController::InvalidAuthenticityToken, with: :render_400

  private

  def render_400
    render plain: '400 Bad Request', status: :bad_request
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def routing
    render plain: '400 Bad Request', status: :bad_request
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/name_basics_controller.rb
require 'datadog/statsd'

class NameBasicsController < ApplicationController
  def index
    start_time = Time.now
    @name_basics = if params[:search].present?
                     NameBasic.where('primary_name ilike ?', "%#{params[:search]}%")
                   else
                     []
                   end
    duration = Time.now - start_time

    if params[:search].present?
      statsd = Datadog::Statsd.new

      statsd.increment('name_basics.search.count')

      statsd.histogram('name_basics.search.time', duration)
    end
  end
end

app/controllers/players_controller.rb
require 'datadog/statsd'

class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]
  caches_action :show, expires_in: 1.hour

  # GET /players
  # GET /players.json
  def index
    start_time = Time.now
    @players = if params[:search].present?
                     Player.where('primary_name ilike ?', "%#{params[:search]}%")
                   else
                     []
                   end
    duration = Time.now - start_time

    if params[:search].present?
      statsd = Datadog::Statsd.new

      statsd.increment('players.search.count')

      statsd.histogram('players.search.time', duration)
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:nconst, :primary_name, :birth_year, :death_year, :primary_profession, :known_for_titles)
    end
end

app/controllers/title_basics_controller.rb
class TitleBasicsController < ApplicationController
  before_action :set_title_basic, only: [:show, :edit, :update, :destroy]

  # GET /title_basics
  # GET /title_basics.json
  def index
    @title_basics = TitleBasic.limit(10)
  end

  # GET /title_basics/1
  # GET /title_basics/1.json
  def show
  end

  # GET /title_basics/new
  def new
    @title_basic = TitleBasic.new
  end

  # GET /title_basics/1/edit
  def edit
  end

  # POST /title_basics
  # POST /title_basics.json
  def create
    @title_basic = TitleBasic.new(title_basic_params)

    respond_to do |format|
      if @title_basic.save
        format.html { redirect_to @title_basic, notice: 'Title basic was successfully created.' }
        format.json { render :show, status: :created, location: @title_basic }
      else
        format.html { render :new }
        format.json { render json: @title_basic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /title_basics/1
  # PATCH/PUT /title_basics/1.json
  def update
    respond_to do |format|
      if @title_basic.update(title_basic_params)
        format.html { redirect_to @title_basic, notice: 'Title basic was successfully updated.' }
        format.json { render :show, status: :ok, location: @title_basic }
      else
        format.html { render :edit }
        format.json { render json: @title_basic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /title_basics/1
  # DELETE /title_basics/1.json
  def destroy
    @title_basic.destroy
    respond_to do |format|
      format.html { redirect_to title_basics_url, notice: 'Title basic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_title_basic
      @title_basic = TitleBasic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def title_basic_params
      params.require(:title_basic).permit(:tconst, :title_type, :primary_title, :original_title, :is_adult, :start_year, :end_year, :runtime_minutes, :genres)
    end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  http_basic_authenticate_with name: 'bostonrb', password: 'ezcater'
  skip_before_action :verify_authenticity_token, only: :create

  def create
    average = params[:average].to_i
    delta = params[:delta].to_i
    interval = rand((average-delta)..(average+delta))
    logger.debug "going to sleep #{interval}"
    start = Time.now
    while Time.now - start < interval.seconds
      slow_operation
    end
    render json: ''
  end

  private

  def slow_operation
    1_000_000.times { Time.new }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/title_basics_helper.rb
module TitleBasicsHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Web Application Performance</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/name_basics/index.html.erb
<h1>Search</h1>

<%= form_tag(name_basics_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag('search') %>
<% end %>

<br>

<% if @name_basics.any? %>
  <%= "#{@name_basics.size} found" %>
<% end %>

<% @name_basics.each do |name_basic| %>
  <ul>
    <li><%= [name_basic.primary_name, name_basic.primary_profession].join(': ') %></li>
  </ul>
<% end %>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nconst %>
    <%= form.text_field :nconst %>
  </div>

  <div class="field">
    <%= form.label :primary_name %>
    <%= form.text_area :primary_name %>
  </div>

  <div class="field">
    <%= form.label :birth_year %>
    <%= form.number_field :birth_year %>
  </div>

  <div class="field">
    <%= form.label :death_year %>
    <%= form.number_field :death_year %>
  </div>

  <div class="field">
    <%= form.label :primary_profession %>
    <%= form.text_area :primary_profession %>
  </div>

  <div class="field">
    <%= form.label :known_for_titles %>
    <%= form.text_area :known_for_titles %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Search</h1>

<%= form_tag(players_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag('search') %>
<% end %>

<br>

<% if @players.any? %>
  <%= "#{@players.size} found" %>
<% end %>

<% @players.each do |player| %>
  <ul>
    <li>
      <%= link_to(player.id, player) %>
      <%= [player.primary_name, player.primary_profession].join(': ') %>
    </li>
  </ul>
<% end %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nconst:</strong>
  <%= @player.nconst %>
</p>

<p>
  <strong>Primary name:</strong>
  <%= @player.primary_name %>
</p>

<p>
  <strong>Birth year:</strong>
  <%= @player.birth_year %>
</p>

<p>
  <strong>Death year:</strong>
  <%= @player.death_year %>
</p>

<p>
  <strong>Primary profession:</strong>
  <%= @player.primary_profession %>
</p>

<p>
  <strong>Known for titles:</strong>
  <% @player.known_for_titles.split(',').map do |x| %>
    <%= link_to(x.strip, TitleBasic.find_by(tconst: x.strip)) %>
  <% end %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/title_basics/_form.html.erb
<%= form_with(model: title_basic, local: true) do |form| %>
  <% if title_basic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(title_basic.errors.count, "error") %> prohibited this title_basic from being saved:</h2>

      <ul>
      <% title_basic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tconst %>
    <%= form.text_field :tconst %>
  </div>

  <div class="field">
    <%= form.label :title_type %>
    <%= form.text_field :title_type %>
  </div>

  <div class="field">
    <%= form.label :primary_title %>
    <%= form.text_area :primary_title %>
  </div>

  <div class="field">
    <%= form.label :original_title %>
    <%= form.text_area :original_title %>
  </div>

  <div class="field">
    <%= form.label :is_adult %>
    <%= form.text_area :is_adult %>
  </div>

  <div class="field">
    <%= form.label :start_year %>
    <%= form.number_field :start_year %>
  </div>

  <div class="field">
    <%= form.label :end_year %>
    <%= form.number_field :end_year %>
  </div>

  <div class="field">
    <%= form.label :runtime_minutes %>
    <%= form.number_field :runtime_minutes %>
  </div>

  <div class="field">
    <%= form.label :genres %>
    <%= form.text_field :genres %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/title_basics/_title_basic.html.erb
<p>
  <strong>Tconst:</strong>
  <%= @title_basic.tconst %>
</p>

<p>
  <strong>Title type:</strong>
  <%= @title_basic.title_type %>
</p>

<p>
  <strong>Primary title:</strong>
  <%= @title_basic.primary_title %>
</p>

<p>
  <strong>Original title:</strong>
  <%= @title_basic.original_title %>
</p>

<p>
  <strong>Is adult:</strong>
  <%= @title_basic.is_adult %>
</p>

<p>
  <strong>Start year:</strong>
  <%= @title_basic.start_year %>
</p>

<p>
  <strong>End year:</strong>
  <%= @title_basic.end_year %>
</p>

<p>
  <strong>Runtime minutes:</strong>
  <%= @title_basic.runtime_minutes %>
</p>

<p>
  <strong>Genres:</strong>
  <%= @title_basic.genres %>
</p>

app/views/title_basics/edit.html.erb
<h1>Editing Title Basic</h1>

<%= render 'form', title_basic: @title_basic %>

<%= link_to 'Show', @title_basic %> |
<%= link_to 'Back', title_basics_path %>

app/views/title_basics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Title Basics</h1>

<table>
  <thead>
    <tr>
      <th>Tconst</th>
      <th>Title type</th>
      <th>Primary title</th>
      <th>Original title</th>
      <th>Is adult</th>
      <th>Start year</th>
      <th>End year</th>
      <th>Runtime minutes</th>
      <th>Genres</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @title_basics.each do |title_basic| %>
      <tr>
        <td><%= title_basic.tconst %></td>
        <td><%= title_basic.title_type %></td>
        <td><%= title_basic.primary_title %></td>
        <td><%= title_basic.original_title %></td>
        <td><%= title_basic.is_adult %></td>
        <td><%= title_basic.start_year %></td>
        <td><%= title_basic.end_year %></td>
        <td><%= title_basic.runtime_minutes %></td>
        <td><%= title_basic.genres %></td>
        <td><%= link_to 'Show', title_basic %></td>
        <td><%= link_to 'Edit', edit_title_basic_path(title_basic) %></td>
        <td><%= link_to 'Destroy', title_basic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Title Basic', new_title_basic_path %>

app/views/title_basics/new.html.erb
<h1>New Title Basic</h1>

<%= render 'form', title_basic: @title_basic %>

<%= link_to 'Back', title_basics_path %>

app/views/title_basics/show.html.erb
<p id="notice"><%= notice %></p>

<% cache @title_basic do %>
  <%= render "title_basic" %>
<% end %>

<%= link_to 'Edit', edit_title_basic_path(@title_basic) %> |
<%= link_to 'Back', title_basics_path %>

app/views/trades/create.html.erb
<h1>Trades#create</h1>
<p>Find me in app/views/trades/create.html.erb</p>